apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lmw-fitness-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/88Warren/lmw-fitness-helmchart.git
    targetRevision: prod-blue
    path: backend
  destination:
    server: https://kubernetes.default.svc
    namespace: lmw-fitness
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true