apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lmw-fitness-helmchart
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:88Warren/lmw-fitness-helmchart.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: lmw-fitness
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true