apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lmw-fitness-pipeline
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  project: default
  source:
    repoURL: https://github.com/88Warren/lmw-fitness-pipeline.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: lmw-fitness
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true